[tool.poetry]
name = "pydantic"
version = "0.1.0"
description = ""
authors = ["axasuser <aa06081986aa@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
